# Site settings
name: "Mobile SDK Labs"
title: Kofax Mobile SDK Labs
email: ethan.bruning@kofax.com
description: > # this means to ignore newlines until "baseurl:"
  These are the lab files for the Kofax Mobile Plateform CBT. These labs will teach
  you about the Mobile SDK and are not intended to teach you how to program in 
  Objective-C or Java.
# baseurl: "/labs" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: ethan_bruning
github_username:  ebruning
paginate: 10

# Build settings
markdown: rdiscount
permalink: pretty
highlighterjek  : true
